### ISSUE TITLE
Replacement for PyPy.js?

### ISSUE THREAD

**Issue by jedie** [micropython/micropython-unicorn#3]
I came across https://www.micropython.org/unicorn/ by accident today. I'm very impressed.

Can't micropython-unicorn be what PyPy.js actually wanted to be?

PyPy.js had the problem that it is simply too big: The loading times are simply too long for practical use. See: https://github.com/pypyjs/pypyjs/issues/196

Currently PyPy.js is not alive, see: https://github.com/pypyjs/pypyjs/issues/213

What would be missing? Think if it possible to manipulate the DOM tree, than it ready, isn't it?!?

**Comment by dpgeorge** [comment]
The unicorn "platform" is less about running Python in the browser and more about *simulating a bare-metal microcontroller in the browser*.

It's probably better to look at the javascript port of MicroPython.  See eg extensions at this PR: https://github.com/micropython/micropython/pull/4603

**Comment by dpgeorge** [comment]
There's now the webassembly port of MicroPython which can run in the browser.  See also the pyscript project by Anaconda.
