### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by hlovatt** [micropython/micropython-unicorn#5]
Is this abandonware?

I ask because nothing much has happened in the repo for years and the version of this software running on the MicroPython website is running a really old version of MicroPython.

I hope the project isn't abandoned as it is a great idea!

**Comment by dpgeorge** [comment]
Even though it's old, it still works :smile: 

But, yes, would be good to keep this repo active.  I've now updated to MicroPythov v1.19.1, see 537518db953f42e3a12104c28c611de0d2d0695f
