### ISSUE TITLE
Error building the python framework

### ISSUE THREAD

**Issue by unclecode** [micropython/micropython-unicorn#6]
I get this error when I run "make CONFIG=pyboard"

`Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
CC ../micropython/py/../lib/utils/printf.c
../micropython/py/../lib/utils/printf.c:109:5: error: '__GI_vsnprintf' specifies less restrictive attributes than its target 'vsnprintf': 'nonnull', 'nothrow' [-Werror=missing-attributes]
  109 | int __GI_vsnprintf(char *str, size_t size, const char *fmt, va_list ap) __attribute__((weak, alias ("vsnprintf")));
      |     ^~~~~~~~~~~~~~
../micropython/py/../lib/utils/printf.c:112:5: note: '__GI_vsnprintf' target declared here
  112 | int vsnprintf(char *str, size_t size, const char *fmt, va_list ap) {
      |     ^~~~~~~~~
cc1: all warnings being treated as errors
make: *** [build_pyboard/py/../lib/utils/printf.o] Error 1`

When I run "make CONFIG=pyboard CFLAGS="-Wno-error" CXXFLAGS="-Wno-error" then I get this:

`Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
CC ../micropython/py/../lib/utils/printf.c
../micropython/py/../lib/utils/printf.c:27:10: fatal error: py/mpconfig.h: No such file or directory
   27 | #include "py/mpconfig.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [build_pyboard/py/../lib/utils/printf.o] Error 1`

I searched and really there is no "mpconfig.h" file in the directory.

**Comment by dpgeorge** [comment]
> I searched and really there is no "mpconfig.h" file in the directory.

You need to run `git submodule update --init` to get the `micropython` submodule.

**Comment by unclecode** [comment]
I have already done that. I shared a gif that shows what I did in ubuntu and the error message. 

![test](https://user-images.githubusercontent.com/12494079/198814270-d44a8c36-8b9d-4842-9a3e-6204c033e441.gif)

**Comment by unclecode** [comment]
I think the loop in the gif may not let you focus doesn't he bug, so I am sharing a screenshot.
![Screenshot 2022-10-29 at 12 45 15 PM](https://user-images.githubusercontent.com/12494079/198814399-d6a98df2-03da-49b6-9b84-883ccc9af5a4.png)

**Comment by dpgeorge** [comment]
OK, thanks, I see the problem.

I've now updated to MicroPython v1.19.1 and tested that it builds.  See 537518db953f42e3a12104c28c611de0d2d0695f

**Comment by unclecode** [comment]
It works beautifully! Thanks
